"""Empirical YRFI priors. Generated by `python -m src.calibrate`. Ship default in-repo."""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Dict

from .config import CFG, ROOT

PACKAGED = Path(__file__).with_name("priors_default.json")


def _empty() -> Dict:
    return {
        "league": {"n": 0, "hits": 0, "raw": 0.49, "p": 0.49, "se": 0.0},
        "two_ace": {"n": 0, "hits": 0, "raw": 0.49, "p": 0.49, "se": 0.0},
        "two_soft": {"n": 0, "hits": 0, "raw": 0.49, "p": 0.49, "se": 0.0},
        "source": "fallback-league",
    }


@lru_cache(maxsize=1)
def load_priors() -> Dict:
    for path in (CFG.data_dir / "priors.json", PACKAGED):
        if path.exists():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                data["loaded_from"] = str(path)
                return data
            except (OSError, json.JSONDecodeError):
                continue
    return _empty()


def yrfi_p(tag: str) -> float:
    block = load_priors().get(tag) or {}
    try:
        p = float(block.get("p", 0.49))
    except (TypeError, ValueError):
        p = 0.49
    return min(0.72, max(0.28, p))


def reload() -> None:
    load_priors.cache_clear()
